name: memoauthapp
description: "biometric app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  app_settings: ^5.1.1
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1
  http: ^1.2.1
  local_auth: ^2.2.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#ffffff"

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "transparent"
  adaptive_icon_foreground: "assets/KDSG.jpeg"
  image_path: "assets/KDSG.jpeg"


flutter:
  uses-material-design: true
  assets:
  - assets/KDSG.jpeg