name: memoauthapp
description: "biometric app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#ffffff"

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/kdsglogo.png"
  image_path: "assets/KDSG.jpeg"


flutter:
  uses-material-design: true
  assets:
  - assets/kdsglogo.png